spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}.env
    vectorstore:
      redis:
        initialize-schema: true
        index-name: lee-vectorstore
        prefix: 'embedding:'
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info

internet:
  websearch:
    searxng:
      url: http://localhost:6080/search
      counts: 10